version: "3.9"  # optional since v1.27.0
services:
  ws:
    build: .
    ports:
      - "3002:3002"
    volumes:
      - ../wavlake-ws/.keys:/usr/src/app/.keys:ro
      - ../wavlake-ws/data:/usr/src/app/data
      - ../wavlake-ws/.env:/usr/src/app/.env